import { Header } from "@/components/Header";
import { Toaster } from "@/components/ui/sonner";
import PrivateRouteProvider from "@/provider/PrivateRouteProvider";
import StoreProvider from "@/provider/StoreProvider";
import { ThemeProvider } from "@/provider/ThemeProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          forcedTheme="light"
          disableTransitionOnChange
        >
          <StoreProvider>
            <PrivateRouteProvider>
              <>
                <Header />
                <main className="min-h-screen">{children}</main>
                <Toaster />
              </>
            </PrivateRouteProvider>
          </StoreProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
